name: mocktailx
description: A set of utility functions over mocktail library.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  mocktail: ^0.1.3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
